### ISSUE TITLE
TachiWeb with other mangasource installation. 

### ISSUE THREAD

**Issue by nearbaskara** [TachiWeb/TachiWeb-Server#11]
So in Tachiyomi (dev), I could install other manga sources in the app. Can I do in here too?

**Comment by null-dev** [comment]
Not currently. I'm working on it, but I'm going to finish sync first before I can implement that here.

**Comment by null-dev** [comment]
Implemented in: https://github.com/Ligerx/TachiWeb-React/commit/6559a9886c7155decd77363547413e049f76b69d
