### ISSUE TITLE
Categories feature incomplete?

### ISSUE THREAD

**Issue by Ligerx** [TachiWeb/TachiWeb-Server#18]
Taking a look at the tachiweb-ui code, I can see features to create, edit, reorder, and delete categories. But I can't find anything for assigning manga to these categories.

Is this just something that hasn't been implemented?

**Comment by null-dev** [comment]
Yep, there is unfortunately no endpoint to add/remove manga from categories yet. Going to work on that as well...

**Comment by null-dev** [comment]
Implemented in `sync` branch
