### ISSUE TITLE
Add persistent Library sorting and filtering flags

### ISSUE THREAD

**Issue by Ligerx** [TachiWeb/TachiWeb-Server#19]
Refer to my implementation of library flags too see what I've already implemented and have working.

I created this based on MangaInfo's flags and the current Tachiyomi app's interface. (I've also left out some flag options that are unused)

[Type definition](https://github.com/Ligerx/TachiWeb-React/blob/9791452fc703e45a11c5e8f538e8922fd44da599/src/types/index.js#L58)
[Example of Library state including flags](https://github.com/Ligerx/TachiWeb-React/blob/9791452fc703e45a11c5e8f538e8922fd44da599/src/redux-ducks/library.js#L48)

If it's hard to understand I can add some extra explanation here.

**Comment by Ligerx** [comment]
Note, I haven't implemented 'LAST_READ' or 'LAST_UPDATED' sort type because I don't believe I have access to the necessary data.

**Comment by null-dev** [comment]
Implemented in `sync` branch. I'll also take a look at providing the info necessary for last_read and last_updated.
