### ISSUE TITLE
Can't build, test fails

### ISSUE THREAD

**Issue by j2ghz** [TachiWeb/TachiWeb-Server#2]
https://github.com/TachiWeb/TachiWeb-Server/blob/master/build.sh#L11
https://github.com/TachiWeb/TachiWeb-Server/blob/67380f35dbbf276ea9ab76a721e82a69a2d28a22/src/test/java/xyz/nulldev/ts/sync/LibraryComparerTest.java#L20

**Comment by null-dev** [comment]
Oh, derp, that's an outdated and broken test, I'll probably just get rid of it for now and replace it with a working test later.
