### ISSUE TITLE
Add option to save reader type to server

### ISSUE THREAD

**Issue by Ligerx** [TachiWeb/TachiWeb-Server#21]
Currently I have a SinglePageReader and WebtoonReader.
I don't have any in-app way of selecting which reader, so I'm defaulting to WebtoonReader.

It would be nice to have a way to select (and persist) which reader you want as a default and per manga.

Another alternative is to only have the WebtoonReader. imo it's the superior way to read

**Comment by null-dev** [comment]
Fixed in `sync` branch
