### ISSUE TITLE
Download Tachiyomi jar Problem

### ISSUE THREAD

**Issue by Snake87r** [TachiWeb/TachiWeb-Server#24]
Hello, i've tried to download the latest build from this address (like writed in the install.md):
https://ci.nulldev.xyz/job/TachiWeb-Server/lastSuccessfulBuild/artifact/TachiServer/build/libs/TachiServer-all-1.0.jar
But I can't download it, I've tried with chrome and microoft edge three times for each browser.

This is the error I've got:

Error 504
Ray ID: 431e98580b5ba869 • 2018-06-28 07:57:08 UTC 
Gateway time-out

You Browser Working
Paris Cloudflare Working
ci.nulldev.xyz Host Error

What happened?
The web server reported a gateway time-out error.

What can I do?
Please try again in a few minutes.

**Comment by null-dev** [comment]
Recently, we have moved to a different build/distribution server so some of our links are outdated.

You can download the newest build by going to this page: http://travis.nd.ax/TachiWeb/TachiWeb-Server/ and clicking on the bottom-most link. Then click on the "server.jar" file to download it.
