### ISSUE TITLE
Binary Jar dl site down?

### ISSUE THREAD

**Issue by happyfilmmaker** [TachiWeb/TachiWeb-Server#25]
The site for the latest binary in the read me seems to be down. Been trying to refresh it for the last few days but kept getting a cloudflare error. I just found this project so I'm not sure what current developments are.

**Comment by null-dev** [comment]
Sorry, I haven't had any time lately and my servers are in a big tangled, mess. You can still find the latest binary here: http://travis.nd.ax/TachiWeb/TachiWeb-Server/39_8788b3542a2f5b804d680bee7165b5f30f135b67/server.jar

Development is paused for this project (and all of my other projects) as I've just been too busy. I'm hoping to get back to working on it soon however!

**Comment by happyfilmmaker** [comment]
Hmm ok, thanks for the link! I'm excited to see where this project can go when you resume.

**Comment by null-dev** [comment]
README updated with fixed download link.
