### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ThePreviousOne** [TachiWeb/TachiWeb-Server#3]
Correct me if I'm wrong, but a lot of the code here is from Tachiyomi. Making it Apache code, meaning your breaking the license terms by not at least including the Apache license in your project. But as Dual licensing is a pain you should really just relicense TachiWeb to Apache

**Comment by null-dev** [comment]
Derp, I considered licensing already but forgot to include the license...

Anyways, since I don't want to deal with putting MIT code in Apache code. I probably will change the license to Apache 2 as both Android and RXPreferences are both in Apache also.

**Comment by null-dev** [comment]
UI and server are now under Apache 2.
