### ISSUE TITLE
Extension/Catalog Not Working

### ISSUE THREAD

**Issue by jimbojnr81** [TachiWeb/TachiWeb-Server#38]
The ReadComicsOnline catalog is throwing up a "Failed to load this catalog" error when trying to load it. I think its probably due to the url of the site changing, it happens all the time to the android app. The url is now https://readcomiconline.to/

As this url is getting changed on a semi regular basis is there a way to be able to manually update the url? rather than having to update the whole app?

**Comment by null-dev** [comment]
It's actually due to the website's bot prevention mechanism kicking in. Our bypass algorithm is currently a little behind compared to Tachiyomi which is why this is happening. I'm looking into upgrading it soon to fix this.

**Comment by kendofriendo** [comment]
the extensions actually don't show up in the catalogue at all for me

**Comment by null-dev** [comment]
You probably just have to restart the application, sometimes the catalogue list doesn't refresh properly after installing an extension.

**Comment by null-dev** [comment]
Should be fixed now.
