### ISSUE TITLE
Remove dummy category

### ISSUE THREAD

**Issue by Ligerx** [TachiWeb/TachiWeb-Server#44]
https://github.com/TachiWeb/TachiWeb-Server/issues/37#issuecomment-504689195
3c8ac9a28977e73c7a3961f68a75022ddd7dbdcc, 34d632aae8fdfb25e546c0f4a9f333f5c313bf46

I know I was originally the one who asked you to include the list of manga not in a category. I realized shortly after it was added that this was at best unneeded and at worst potentially misleading.

The only time this could be necessary is if the client re-fetches all the category data every time categories are edited, but this is super inefficient and not the approach I'm taking with the front end code.

**Comment by null-dev** [comment]
Done in https://github.com/TachiWeb/TachiWeb-Server/commit/2c4bd577e40a89a84f1d58f7ffbf92afa954d914
