### ISSUE TITLE
Filter default is filter out instead of undefined

### ISSUE THREAD

**Issue by Omoroca13** [TachiWeb/TachiWeb-Server#46]
Hi first thx for this great application. I searched for something like this for a long time ^^

The default for filter options is to filter out (screenshot) instead of being undefined could this be changed ? tyvm for reading
![Screenshot_2019-08-23_23-39-46](https://user-images.githubusercontent.com/54456290/63625291-77473b00-c5ff-11e9-9425-907d5bc786e0.png)

**Comment by null-dev** [comment]
Which source/extension is this?

**Comment by Omoroca13** [comment]
Manga Rock 
happens for all my Catalogs though

**Comment by Omoroca13** [comment]
Oh and this is the server version open in firefox (with a dark background add-on)
i tested it in a plain chromium just now with the same result

**Comment by null-dev** [comment]
So this is actually just a visual difference between TachiWeb and Tachiyomi. In TachiWeb, those checkboxes are actually in the "undefined" state, not the "filter out" state. Here is what each of the states look like:

![checkboxes](https://user-images.githubusercontent.com/9571936/63725217-be177980-c827-11e9-8094-e82bcfab2dc3.png)

**Comment by Omoroca13** [comment]
Oh ok thank you.
I thought I tested that but i must have messed it up. 
It is a bit confusing though.
