### ISSUE TITLE
2 API calls with the same name (editCategories)

### ISSUE THREAD

**Issue by Ligerx** [TachiWeb/TachiWeb-Server#47]
@tachiweb/api-client/lib/api.js

There's 2 `editCategories` functions. ~~Haven't tried using the exposed api yet, so idk if this is a breaking bug or not.~~ Functionally, it works as expected.

**Comment by null-dev** [comment]
Are you talking about the `editCategory` and `editCategories` functions? Those two functions behave differently. One of them allows editing a single category, and the other allows for atomically editing multiple categories.

**Comment by Ligerx** [comment]
Nevermind, I got confused. The api file has a `DefaultApiFetchParamCreator` object and a `DefaultApi` object, so there were duplicate method names when `ctrl+f` searching.
