### ISSUE TITLE
Error sending cached Cover

### ISSUE THREAD

**Issue by calgara12** [TachiWeb/TachiWeb-Server#9]
Hello, when I'm trying to download im getting this exception:
![capture](https://user-images.githubusercontent.com/28657023/30529191-2591004c-9c3b-11e7-8221-380ffe97f1dd.PNG)

Im running Ubuntu server 16.04.

Thank you for your help :]

**Comment by null-dev** [comment]
I think this error is normal. Does anything look broken?

**Comment by calgara12** [comment]
Ok, i did some investigation. I thought that the download wouldn work, but thats not true, The files are downloaded inside the folder ```android-compat/extappdata/TachiWeb/downloads/```

But nothing shows up in the library, do you have an idea why?

**Comment by null-dev** [comment]
Downloading chapters doesn't save the manga into the library. You have to
press the blue, round "bookmark" button on the manga's info screen.

Just curious, have you used the original Tachiyomi app?

**Comment by calgara12** [comment]
Oh sorry i didnt know that. 
No not yet. But i'm trying to set everything up :]

Thanks again!

**Comment by null-dev** [comment]
Ok, if you have an Android phone, I recommend you first try out the mobile app as this program is designed to be a complete copy of the it. 

Thanks, for reporting these bugs!

**Comment by calgara12** [comment]
I will definitely do so :] Thanks.

**Comment by kawaii-senpai** [comment]
Is there any ways to read manga in desktop offline?
